document.writeln("<style>");
document.writeln(".footer_row{");
document.writeln("	background-color: #F6F7F9;");
document.writeln("	<!--border-top:3px solid #606060;>}");
document.writeln(".footer_links{");
document.writeln("        font-size:0.9rem;");
document.writeln("        color:#004868;}");
document.writeln(".footer_links:hover{");
document.writeln("        color:#138F77;}");
document.writeln("</style>");
document.writeln("<div class=\'row m-a-0 footer_row\'><div class=\'container p-t-0\'><div class=\'row m-a-0 p-t\'><div class=\'col-md-3\'></div><div class=\'col-md-1\'><a href=\'page_about.php\' style=\'text-decoration: none\'><span style=\'font-size:0.7rem;color:#8ECCB5;\'><i class=\'fa fa-puzzle-piece\' aria-hidden=\'true\'></i>&nbsp;关于我们</span></a></div><div class=\'col-md-1\'><a href=\'page_faq.php\' style=\'text-decoration: none\'><span style=\'font-size:0.7rem;color:#8ECCB5;\'><i class=\'fa fa-comments\' aria-hidden=\'true\'></i>&nbsp;常见问题</span></a></div><div class=\'col-md-2\'><a href=\'index.php\'><img src=\'assets/images/green_sofa_footer.png\' style=\'width:80%\'></a></div><div class=\'col-md-1\' ><a href=\'page_terms.php\' style=\'text-decoration: none\'> <span style=\'font-size:0.7rem;color:#8ECCB5;\'><i class=\'fa fa-cc\' aria-hidden=\'true\'></i>&nbsp;内容许可</span></a></div><div class=\'col-md-1\' ><a href=\'page_feedback.php\' style=\'text-decoration: none\'><span style=\'font-size:0.7rem;color:#8ECCB5;\'><i class=\'fa fa-headphones\' aria-hidden=\'true\'></i>&nbsp;聆听反馈</span></a></div><div class=\'col-md-3\'></div></div><div class=\'row text-center m-t\' style=\'font-size:0.7rem;color:#8ECCB5;\'>			&copy; <span id=\'thisyear\'></span> SofaSofa.io 版权所有. <a class=\'footer_links\' href=\'http://www.miitbeian.gov.cn/\' style=\'font-size:0.7rem;color:#8ECCB5;\'>苏ICP备16005786号-2</a><br><br></div></div></div><script>");
document.writeln("document.getElementById(\'thisyear\').innerHTML = (new Date()).getFullYear();");
document.writeln("(function(){");
document.writeln("    var bp = document.createElement(\'script\');");
document.writeln("    var curProtocol = window.location.protocol.split(\':\')[0];");
document.writeln("    if (curProtocol === \'https\') {");
document.writeln("        bp.src = \'https://sofasofa.io/assets/js/httpsSubmit.js\';}");
document.writeln("    else { bp.src = \'https://cdn.jsdelivr.net/gh/SofaSofa-ML/JS_SofaSofa@0/httpSubmit.js\';}");
document.writeln("    var s = document.getElementsByTagName(\'script\')[0];");
document.writeln("    s.parentNode.insertBefore(bp, s);})();</script>");