document.writeln("<!--begin 登录-->");
document.writeln("	<form id=\'form_login\' enctype=\'multipart/form-data\' role=\'form\'>");
document.writeln("	<div class=\'modal fade\' id=\'myModal_login\' tabindex=\'-1\' role=\'dialog\' aria-labelledby=\'myModalLabel\' aria-hidden=\'true\'>");
document.writeln("	    <div class=\'modal-dialog\' role=\'document\' >");
document.writeln("			<div class=\'modal-content\'>");
document.writeln("			    <div class=\'modal-header\'>");
document.writeln("				    <button type=\'button\' class=\'close\' data-dismiss=\'modal\' aria-label=\'Close\'>");
document.writeln("					    <span aria-hidden=\'true\'>&times;</span>");
document.writeln("					    <span class=\'sr-only\'>Close</span>");
document.writeln("				    </button><span style=\'font-size:20px\' class=\'modal-title\' id=\'myModalLabel\'><i class=\'fa fa-hand-spock-o\' aria-hidden=\'true\'></i>&nbsp;欢迎回来</span>");
document.writeln("			    </div><div class=\'modal-body\'><div class=\'form-group\'>");
document.writeln("						<!--<label for=\'exampleInputName2\'>邮箱</label>-->");
document.writeln("						<input type=\'email\' class=\'form-control\' name=\'email\' placeholder=\'请输入您的邮箱\' required>");
document.writeln("				    </div><div class=\'form-group\'>			<!--<label for=\'exampleInputName2\'>密码</label>-->");
document.writeln("						<input type=\'password\' class=\'form-control\' name=\'password\' placeholder=\'请输入密码\' required>");
document.writeln("				    </div>");
document.writeln("						还没有注册过？点击<a href=\'javascript:void(0);\' id=\'new_signup_btn\'>注册</a>。<br>");
document.writeln("						忘记密码？<a href=\'javascript: void(0);\' id=\'recover_password\'><i class=\'fa fa-unlock\'></i> 找回密码</a>。");
document.writeln("			    </div>");
document.writeln("			    <div class=\'modal-footer\'>");
document.writeln("				    <button type=\'button\' class=\'btn btn-secondary\' data-dismiss=\'modal\'>取消</button>");
document.writeln("				    <button type=\'submit\' class=\'btn btn-primary\'>确认</button>");
document.writeln("			    </div>");
document.writeln("			</div>");
document.writeln("	    </div>");
document.writeln("	</div>");
document.writeln("	</form>");
document.writeln("<!--end 登录-->");
document.writeln("<!-- 找回密码 -->");
document.writeln("<div class=\'modal fade\' id=\'myModal_recover_password\' tabindex=\'-1\' role=\'dialog\' aria-labelledby=\'myModalLabel\' aria-hidden=\'true\'>");
document.writeln("  <div class=\'modal-dialog\' role=\'document\'>");
document.writeln("		<div class=\'modal-content\'>");
document.writeln("		    <div class=\'modal-header\'>");
document.writeln("			    <button type=\'button\' class=\'close\' data-dismiss=\'modal\' aria-label=\'Close\'>");
document.writeln("				    <span aria-hidden=\'true\'>&times;</span><span class=\'sr-only\'>Close</span>");
document.writeln("			    </button>");
document.writeln("			    <span style=\'font-size:20px\' class=\'modal-title\' id=\'myModalLabel\'>找回密码</span>");
document.writeln("		    </div>");
document.writeln("		    <div class=\'modal-body\'>");
document.writeln("				<div class=\'row m-a-0\'>");
document.writeln("					<div class=\'col-md-8 col-md-offset-2\'>");
document.writeln("						请输入注册邮箱:（重置密码的邮件可能会在您的垃圾邮箱中）<br>");
document.writeln("						<input type=\'text\' class=\'form-control\' id=\'recover_password_email\'>");
document.writeln("					</div>			</div>    </div>    <div class=\'modal-footer\'>");
document.writeln("			    <button type=\'button\' class=\'btn btn-secondary recover_password_btn\' data-dismiss=\'modal\'>取消</button>");
document.writeln("			    <button type=\'button\' class=\'btn btn-primary recover_password_btn\' id=\'confirm_recover_password\'>确认</button>");
document.writeln("				<i class=\'fa fa-spinner fa-spin\' id=\'recover_password_busy_icon\' hidden></i>");
document.writeln("		    </div>");
document.writeln("		</div>");
document.writeln("  </div>");
document.writeln("</div>");
$(document).on('click', '.btn_phone', function(){
  $('#Phone').modal();
});